name: CI

on:
  push:

jobs:
  release:
    name: Create release
    if: >-
      forgejo.ref_type == 'tag' &&
      forgejo.repository_owner == 'charlesrocket'

    uses: charlesrocket/reusable/.forgejo/workflows/release.yml@trunk
    with:
      skip-assets: true
