name: Lint

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Lint
        uses: arduino/arduino-lint-action@v3
        with:
          library-manager: update
          compliance: strict
