name: Lint

on:
  pull_request:
  push:
  schedule:
    - cron: "0 11 13 */2 *"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          compliance: strict
